---
title: "Notebook for the development of the artificial testing pipeline"
output: html_notebook
---

# Initialize parameters
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/fabio/projects/aggressotype/code/galaina/')
```

```{r}
library(ConfigParser)
source('./for_testing/artificial_generator_data_and_factor.R')
factor_n = 7;
prob = NULL;
lB = 0.1
uB = 1;
frac_variable_discreet = 0.5;
# range_bin_discreet = 2:5;
range_bin_discreet = 2:4;
#rmv parameters
n = 1000;
# g = NULL;
impurity = 0; range.indicators = 3:10; lambda.min = 0.1; lambda.max = 1; sd.residual = 1;
first_random_seed = 1000;
random_seed_update_parameter = 10
```

# Simulate Data

## Create a DAG
A random DAG, serving as the true DAG in latent space
```{r}
if (is.null(prob)) {
  prob <- 2 / (factor_n - 1)
}

random_seed_n <- first_random_seed  # FG for controlling random sampling
set.seed(random_seed_n)  # FG set random generator seed
g <- randomDAG(n = factor_n, prob = prob, lB = lB, uB = uB)
random_seed_n <- update_random_seed(random_seed_n, random_seed_update_parameter)  # FG update random seed
```

## Simulate data and latent factor loadings from DAG 
```{r}
# true CPDAG
# g.cpdag <- dag2cpdag(g)
## generate data
set.seed(random_seed_n)  # FG set random generator seed

data.obs <- rmvCopulaFactorModel(
  n = n,
  g = g,
  impurity = impurity,
  range.indicators = range.indicators,
  lambda.min = lambda.min,
  lambda.max = lambda.max,
  sd.residual = sd.residual,
  first_random_seed = random_seed_n,
  random_seed_update_parameter = random_seed_update_parameter
)
# list(data = Y[,-(1:pl)], Sigma = sigma, index_more = index_more, Lambda = Lamda.pure)

random_seed_n <- update_random_seed(random_seed_n, random_seed_update_parameter)  # FG update random seed
# mapping from latents to response variables
# Lambda <- (data.obs$Lambda != 0) * 1
Lambda <- (data.obs[["Lambda"]] != 0) * 1
# data in response space (fully Gaussian)
# Z <- data.obs$data
Z <- data.obs[["data"]]
# Z <- as.data.frame(Z)
# data in observed space (mixed continuous and ordinal)
var_n <- ncol(Z)
```
### Discretize some randomly selected variables 
Generate data Y in observed space (mixed continuous and ordinal)
```{r}
# library(bnlearn)
ZZ <- data.frame(Z)
Y <- Z
set.seed(random_seed_n)  # FG set random generator seed
sampleResult <- sample(x = 1:var_n, size = round(var_n * frac_variable_discreet))
random_seed_n <- update_random_seed(random_seed_n, random_seed_update_parameter)  # FG update random seed
for (i in sampleResult) {
  set.seed(random_seed_n)  # FG set random generator seed
  # TODO understand why now we need to put Z as dataframe
  cat(i)
  nbins <- sample(range_bin_discreet + 1, 1)
  random_seed_n <- update_random_seed(random_seed_n, random_seed_update_parameter)  # FG update random seed
  Y[, i] <- matrix(unlist(infotheo::discretize(ZZ[, i], breaks = nbins)), byrow = FALSE, nrow = n)
  # Y[, i] <- matrix(unlist(discretize(as.data.frame(Z[, i]), nbins = sample(range_bin_discreet, 1))), byrow = FALSE, nrow = n)
  # Y[, i] <- matrix(
  #   unlist(discretize(as.data.frame(Z[, i]), breaks = sample(range_bin_discreet, 1))),
  #   byrow = FALSE, nrow = n
  # )
}
```